name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-${{ hashFiles('museum_search_app/buildozer.spec') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            libssl-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            libncursesw5-dev \
            libffi-dev \
            uuid-dev \
            libffi8 \
            lld \
            libtool \
            autoconf \
            automake \
            openjdk-17-jdk

      - name: Install Python dependencies
        run: |
          pip install buildozer
          pip install cython==0.29.33
          pip install kivymd
          pip install python-for-android

      - name: Build APK
        working-directory: museum_search_app
        run: |
          echo "y" | buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Find APK file
        id: find_apk
        run: |
          APK_FILE=$(find museum_search_app/bin -name "*.apk" -type f | head -n 1)
          if [ -z "$APK_FILE" ]; then
            echo "No APK file found!"
            ls -la museum_search_app/bin/ || echo "No bin directory"
            exit 1
          fi
          echo "filename=$APK_FILE" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_FILE"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ steps.find_apk.outputs.filename }}
          retention-days: 30

      - name: Show build info
        run: |
          echo "APK built successfully!"
          echo "Location: ${{ steps.find_apk.outputs.filename }}"
          ls -la museum_search_app/bin/