name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: museum_search_app
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 30

      - name: Show APK location
        run: |
          echo "APK built successfully!"
          echo "Location: ${{ steps.buildozer.outputs.filename }}"
          ls -la museum_search_app/bin/ || true